# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=26.2.0.11-beta

# Additional Dependencies Properties
# iris, check https://modrinth.com/mod/iris/versions?g=26.2&l=neoforge
dep.iris=1.11.2+26.2-neoforge
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=neoforge
dep.yacl=3.9.5+26.2-neoforge
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.2&l=neoforge
dep.sodium=mc26.2-0.9.1-neoforge
# mossylib, check https://modrinth.com/mod/mossylib/versions?g=26.2&l=neoforge
dep.mossylib=1.5.0+26.2+neoforge
